### ISSUE TITLE
Include REP pages in mirror

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/mirror#13]
It would be good if the REP HTML pages would also be replicated to all mirrors.

That doesn't appear to be the case right now, and with `docs.ros.org` going down, it would appear `www.ros.org` also goes down, which makes the REPs inaccessible.

**Comment by tfoote** [comment]
I don't think it's worth the effort to add mirroring infrastructure. 

The REP content is small a few MB and is entirely generated from the github repo: https://github.com/ros-infrastructure/rep to reproduce it locally you just have to run `make` with docutils installed after cloning it.
