### ISSUE TITLE
EU mirror off-line

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/mirror#21]
(I seem to recall there was a dedicated venue for reporting infrastructure issues, but I can't find it, or I'm looking in the wrong place(s))

It looks like `mirror-eu.packages.ros.org` is off-line. Or at least it doesn't respond to `GET`s.

**Comment by gavanderhoorn** [comment]
Friendly ping?

**Comment by tfoote** [comment]
We [decommissioned that machine](https://wiki.ros.org/action/diff/Mirrors?action=diff&rev1=103&rev2=104) when that EC2 instance aged out. I recommend using the Freiburg one: http://wiki.ros.org.ros.informatik.uni-freiburg.de/

**Comment by gavanderhoorn** [comment]
The wiki diff removes the wiki EU mirror. I guess the same machine is used for the apt mirror?

I can't find an announcement of this with some quick googling, but if it is: it's still listed [here](https://wiki.ros.org/ROS/Installation/UbuntuMirrors#OSRF-1).
