### ISSUE TITLE
use of import has been discontinued

### ISSUE THREAD

**Issue by kfechter** [ros-infrastructure/mirror#4]
I followed the steps to install the prerequisites on server 14.04, but when it comes to running sudo puppet apply, it throws an error 

Error: Evaluation Error: Use of 'import' has been discontinued in favor of a manifest directory. See http://links.puppetlabs.com/puppet-import-deprecation at

**Comment by tfoote** [comment]
This will need to be updated for Trusty or newer. 

Related documentation: https://ask.puppet.com/question/10975/for-node-definitionclassification-what-is-the-successor-to-import-nodespp-now-that-import-is-deprecated/

**Comment by tfoote** [comment]
As a short term workaround I've updated the readme to say to force the installation of puppet 3.8.7. 4bf76651be67bd16f19681121c1a47f80bc0b22b

**Comment by kfechter** [comment]
sweet. I haven't tried setting it up with the new instructions, mostly because I graduated and haven't done any robotics things lately.

**Comment by kfechter** [comment]
I'm going to close this since I'm not affected by it anymore.

**Comment by tfoote** [comment]
Thanks, although there's a workaround. I'd like to keep this open since we will need to resolve it before we upgrade. It's important to know about and will effect others.

**Comment by k-okada** [comment]
I have received `ROS Mirror Out of Date` email and try to follow the https://github.com/ros-infrastructure/mirror document, 
```
sudo apt-get install ruby ##rubygems is not foun don 14.04
sudo gem install puppet --no-ri --no-rdoc -v 3.8.7
sudo puppet module install puppetlabs/apache
sudo puppet module install puppetlabs/rsync
sudo puppet module install puppet-unattended_upgrades
```
But running puppet (3.8.7) on 14.04 did not work as follows, and also 4.10.12 / 5.5.2 shows different errors., so that I have rto e-configure our mirror with simple rsync script.

How did everyone configture the mirrors? Did they uses 12.04 machine? did they installed specific version of puppet modules? or did they have fixed repository?

```
ubuntu@ip-172-31-42-117:~/mirror$ sudo puppet applyros_mirror.pp --modulepath=/etc/puppet/modules:/usr/share/puppet/modules:.
        ldapname is deprecated and will be removed in a future version
        Facter::Util::EC2.has_euca_mac? is deprecated; see the Facter::EC2 classes instead
        Facter::Util::EC2.has_openstack_mac? is deprecated; see the Facter::EC2 classes instead
        Facter::Util::EC2.has_ec2_arp? is deprecated; see the Facter::EC2 classes instead
        Error loading fact /usr/lib/ruby/vendor_ruby/facter/macosx.rb:  cannot load such file -- cfpropertylist
        Warning: The use of 'import' is deprecated at   /home/ubuntu/mirror/ros_mirror.pp:3. See http://links.puppetlabs.com/puppet-import-deprecation (at /var/lib/gems/1.9.1/gems/puppet-3.8.7/lib/puppet/parser/parser_support.rb:110:in `import')
        Error: Syntax error at 'Hash'; expected ')' at /etc/puppet/modules/apt/manifests/init.pp:6 on node ip-172-31-42-117.us-west-2.compute.internal
        Error: Syntax error at 'Hash'; expected ')' at /etc/puppet/modules/apt/manifests/init.pp:6 on node ip-172-31-42-117.us-west-2.compute.internal

```
